[variables]
PHP_VERSION = "8.2"

[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev && php artisan config:cache && php artisan route:cache"

[deploy]
startCommand = "php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
APP_ENV = "production"