[variables]
PHP_VERSION = "8.2"

[build]
# Command yang dijalankan saat build
builder = "NIXPACKS"

[deploy]
# Command yang dijalankan setelah build selesai (sekali per deploy)
postDeploy = """
php artisan migrate --force
php artisan storage:link
php artisan config:cache
php artisan route:cache
php artisan view:cache
"""